//
//  DataModels.h
//
//  Created by   on 2017/4/14
//  Copyright (c) 2017 __MyCompanyName__. All rights reserved.
//

#import "LoginBaseClass.h"
#import "ForCategoricalDataListCategory.h"
#import "ForCategoricalDataBaseClass.h"
#import "ForCategoricalDataSecondNav.h"
#import "CollectionBaseClass.h"
#import "CollectionResultList.h"
#import "CollectionData.h"
#import "SearchBaseClass.h"
#import "SearchResultList.h"
#import "SearchPagingList.h"
#import "MessageBaseClass.h"
#import "MessageResultList.h"
#import "MessageData.h"
#import "HomeNews.h"
#import "HomeBaseClass.h"
#import "HomeRecommend.h"
#import "HomeAd2.h"
#import "HomeAds.h"
#import "HomeAd1.h"
#import "HomeAd4.h"
#import "HomeHot.h"
#import "HomeAd3.h"
#import "MyInfo.h"
#import "MyBaseClass.h"
#import "GoodsDetailsListComment.h"
#import "GoodsDetailsMap.h"
#import "GoodsDetailsComm.h"
#import "GoodsDetailsBaseClass.h"
#import "ProductEvaluationBaseClass.h"
#import "ProductEvaluationResultList.h"
#import "ProductEvaluationListComment.h"
#import "ShoppingCarComm.h"
#import "ShoppingCarBaseClass.h"
#import "ShoppingCarList.h"
