//
//  DataModels.h
//
//  Created by   on 2017/4/14
//  Copyright (c) 2017 __MyCompanyName__. All rights reserved.
//

#import "LoginBaseClass.h"
#import "ForCategoricalDataListCategory.h"
#import "ForCategoricalDataBaseClass.h"
#import "ForCategoricalDataSecondNav.h"
#import "CollectionBaseClass.h"
#import "CollectionResultList.h"
#import "CollectionData.h"
#import "SearchBaseClass.h"
#import "SearchResultList.h"
#import "SearchPagingList.h"
#import "MessageBaseClass.h"
#import "MessageResultList.h"
#import "MessageData.h"
#import "HomeBaseClass.h"
#import "HomeAd6.h"
#import "HomeNews.h"
#import "HomeAd1.h"
#import "HomeRecommend.h"
#import "HomeAd4.h"
#import "HomeHot.h"
#import "HomeAd7.h"
#import "HomeAd2.h"
#import "HomeAd5.h"
#import "HomeAd3.h"
#import "HomeAds.h"
#import "MyInfo.h"
#import "MyBaseClass.h"
#import "GoodsDetailsListComment.h"
#import "GoodsDetailsMap.h"
#import "GoodsDetailsComm.h"
#import "GoodsDetailsBaseClass.h"
#import "GoodsDetailsListAttribute.h"
#import "ProductEvaluationBaseClass.h"
#import "ProductEvaluationResultList.h"
#import "ProductEvaluationListComment.h"
#import "ShoppingCarComm.h"
#import "ShoppingCarBaseClass.h"
#import "ShoppingCarList.h"
#import "AddressBaseClass.h"
#import "AddressList.h"
#import "ShoppingSettlementBaseClass.h"
#import "ShoppingSettlementAttr.h"
#import "ShoppingSettlementList.h"
#import "ShoppingSettlementCarts.h"
#import "ShoppingSettlementMapAddress.h"
#import "ShoppingSettlementListAddress.h"
#import "PayBaseClass.h"
#import "BasicInformationInfo.h"
#import "BasicInformationBaseClass.h"
#import "OrderListCommodity.h"
#import "OrderListResultList.h"
#import "OrderListPagingList.h"
#import "OrderListBaseClass.h"
#import "OrderDetailsCommodity.h"
#import "OrderDetailsMap.h"
#import "OrderDetailsBaseClass.h"
#import "WalletBaseClass.h"
#import "Top_UpBaseClass.h"
#import "Top_UpResultList.h"
#import "Top_UpPagingList.h"
#import "WalletDetailsBaseClass.h"
#import "WalletDetailsResultList.h"
#import "WalletDetailsPagingList.h"
#import "MyInformationDataBaseClass.h"
#import "MessageNumberBaseClass.h"
#import "GFMSBaseClass.h"
#import "GFMSOrderMap.h"
#import "ChildProductDetailsMap.h"
#import "ChildProductDetailsBaseClass.h"


